name: Publish Docker Image to GHCR
on:
  push:
    tags:
      - "v*.*.*" # run only on full semver tags
permissions:
  contents: read
  packages: write
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract version parts
        id: meta
        shell: bash
        run: |
          VER="${GITHUB_REF_NAME#v}"
          echo "tag=${VER}" >> "$GITHUB_OUTPUT"
          MAJOR="${VER%%.*}"
          REMAINDER="${VER#${MAJOR}.}"
          MINOR="${REMAINDER%%.*}"
          echo "major=${MAJOR}" >> "$GITHUB_OUTPUT"
          echo "majorMinor=${MAJOR}.${MINOR}" >> "$GITHUB_OUTPUT"
      - name: Set Repo Owner to Lowercase
        run: echo "REPO_OWNER=$(echo ${GITHUB_REPOSITORY_OWNER} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: Docker metadata (labels)
        id: meta_labels
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.REPO_OWNER }}/fax-ui
          labels: |
            org.opencontainers.image.title=fax-ui
            org.opencontainers.image.url=https://github.com/${{ github.repository }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ steps.meta.outputs.tag }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          build-args: |
            APP_VERSION=${{ steps.meta.outputs.tag }}
          push: true
          labels: ${{ steps.meta_labels.outputs.labels }}
          tags: |
            ghcr.io/${{ env.REPO_OWNER }}/fax-ui:${{ steps.meta.outputs.tag }}
            ghcr.io/${{ env.REPO_OWNER }}/fax-ui:${{ steps.meta.outputs.majorMinor }}
            ghcr.io/${{ env.REPO_OWNER }}/fax-ui:${{ steps.meta.outputs.major }}
            ghcr.io/${{ env.REPO_OWNER }}/fax-ui:latest
